# Setup
title:        Warframe Builds
tagline:      All awsome Warframe builds
baseurl:      "/warframebuild"
paginate:     10

# About/contact
author:
  name:       zoulls
  url:        http://zoulls.github.io/warframebuild/

# Gems
gems:
  - jekyll-paginate

#Others
markdown: redcarpet

# Tag
tag_page_layout: tag_page
tag_page_dir: tag