# Setup
title:        Warframe Builds
tagline:      All awsome Warframe builds
baseurl:      "/warframebuild"
paginate:     10
timezone:     Europe/Paris
exclude:      [Gemfile, Gemfile.lock]

# About/contact
authors:
    - name: Zoulls
      url: https://github.com/zoulls
    - name: Disqus
      url: https://github.com/disqus

# Gems
gems:
  - jekyll-paginate
  - jekyll-assets

#Others
markdown: redcarpet

# Tag
tag_page_layout: tag_page
tag_page_dir: tag
