# Setup
title:        Warframe Builds
tagline:      All awsome Warframe builds
baseurl:      "/warframebuild"
paginate:     10
timezone:     Europe/Paris
exclude:      [Gemfile, Gemfile.lock, rakefile.rb, README.md]

# About/contact
authors:
    - name: Zoulls
      url: https://github.com/zoulls
    - name: Disqus
      url: https://github.com/disqus

# Gems
gems:
  - jekyll-paginate
  - jekyll-assets

#Others
markdown: redcarpet

# Tag
tag_page_layout: tag_page
tag_page_dir: tag

# Asset
assets:
  baseurl: /warframebuild/assets

# Picture
picture:
  source: assets
  output: generated
  markup: picture
  presets:
    # Full width pictures
    default:
      ppi: [1, 1.5]
      attr:
        class: blog-full
        itemprop: image
      source_lrg:
        media: "(min-width: 40em)"
        width: 700
      source_med:
        media: "(min-width: 30em)"
        width: 450
      source_default:
        width: 350
        height: 200
    # Half width pictures
    half:
      ppi: [1, 1.5]
      attr:
        data-location: "{{location}}"
        data-active: nil
      source_lrg:
        media: "(min-width: 40em)"
        width: 400
      source_med:
        media: "(min-width: 30em)"
        width: 250
      source_default:
        width: 350
    # Self-set resolution sources. Useful if you don't want a 1:1 image size to dppx ratio.
    gallery:
      source_wide_hi:
        media: "(min-width: 40em) and (min-resolution: 1.5dppx)"
        width: 900
        height: 600
      source_wide:
        media: "(min-width: 40em)"
        width: 600
        height: 400
      source_default:
        width: 250
        height: 250